namespace TaleWorlds.MountAndBlade;

public delegate void GetFocusableObjectInteractionTextsDelegate(Agent requesterAgent, IFocusable focusableObject, bool isInteractable, out FocusableObjectInformation focusableObjectInformation);
