using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;
using TaleWorlds.Core;
using TaleWorlds.DotNet;

[assembly: InternalsVisibleTo("TaleWorlds.MountAndBlade.AutoGenerated")]
[assembly: InternalsVisibleTo("TaleWorlds.MountAndBlade.Multiplayer")]
[assembly: InternalsVisibleTo("TaleWorlds.Generator.Bannerlord")]
[assembly: DefineAsEngineStruct(typeof(AgentState), "Agent_state", false, null, null)]
[assembly: DefineAsEngineStruct(typeof(AgentMovementMode), "Agent_movement_modes", true, "amm", null)]
[assembly: DefineAsEngineStruct(typeof(AgentControllerType), "Agent_controller_type", false, null, null)]
[assembly: DefineAsEngineStruct(typeof(DamageTypes), "Damage_type", false, "dt", null)]
[assembly: DefineAsEngineStruct(typeof(AgentAttackType), "Agent_attack_type", false, "aat", null)]
[assembly: DefineAsEngineStruct(typeof(StrikeType), "Strike_type", false, "st", null)]
[assembly: DefineAsEngineStruct(typeof(ItemFlags), "Item_flags", false, "itf", null)]
[assembly: DefineAsEngineStruct(typeof(WeaponFlags), "Weapon_flags", false, "wf", null)]
[assembly: DefineAsEngineStruct(typeof(WeaponClass), "Weapon_class", false, "itc", null)]
[assembly: DefineAsEngineStruct(typeof(Equipment.UnderwearTypes), "Underwear_mesh_type", false, null, null)]
[assembly: DefineAsEngineStruct(typeof(BodyProperties), "Body_properties", false, null, null)]
[assembly: DefineAsEngineStruct(typeof(DynamicBodyProperties), "Dynamic_body_properties", false, null, null)]
[assembly: DefineAsEngineStruct(typeof(StaticBodyProperties), "Static_body_properties", true, null, null)]
[assembly: DefineAsEngineStruct(typeof(MissionInitializerRecord), "Mission_initializer_record", false, null, null)]
[assembly: DefineAsEngineStruct(typeof(EquipmentIndex), "Weapon_slots_in_equipment", false, "wsie", null)]
[assembly: AssemblyCompany("TaleWorlds.MountAndBlade")]
[assembly: AssemblyConfiguration("Shipping_Client")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0")]
[assembly: AssemblyProduct("TaleWorlds.MountAndBlade")]
[assembly: AssemblyTitle("TaleWorlds.MountAndBlade")]
[assembly: AssemblyVersion("1.0.0.0")]
